# Generated by Django 3.1.2 on 2020-10-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSensorConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureThreshold', models.FloatField(verbose_name='温度阈值')),
                ('concentrationThreshold', models.FloatField(verbose_name='浓度阈值')),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('smokescope', models.FloatField(verbose_name='烟雾浓度')),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
